# Generated by Django 3.1 on 2020-11-01 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField(null=True)),
                ('objectid', models.BigIntegerField(null=True)),
                ('pau_name', models.CharField(max_length=254, null=True)),
                ('village', models.CharField(max_length=254, null=True)),
                ('pau_code', models.CharField(max_length=254, null=True)),
                ('vill_code', models.CharField(max_length=254, null=True)),
                ('st_name', models.CharField(max_length=254, null=True)),
                ('st_code', models.FloatField(null=True)),
                ('loc_name', models.CharField(max_length=254, null=True)),
                ('loc_code', models.CharField(max_length=254, null=True)),
                ('au_name', models.CharField(max_length=254, null=True)),
                ('au_code', models.CharField(max_length=254, null=True)),
                ('elec', models.FloatField(null=True)),
                ('phone', models.FloatField(null=True)),
                ('wc', models.FloatField(null=True)),
                ('oid_join', models.CharField(max_length=254, null=True)),
                ('state', models.CharField(max_length=254, null=True)),
                ('county', models.CharField(max_length=254, null=True)),
                ('au', models.CharField(max_length=254, null=True)),
                ('pau', models.CharField(max_length=254, null=True)),
                ('m_0_4', models.BigIntegerField(null=True)),
                ('f_0_4', models.BigIntegerField(null=True)),
                ('m_5_14', models.BigIntegerField(null=True)),
                ('f_5_14', models.BigIntegerField(null=True)),
                ('m_15_24', models.BigIntegerField(null=True)),
                ('f_15_24', models.BigIntegerField(null=True)),
                ('m_25_44', models.BigIntegerField(null=True)),
                ('f_25_44', models.BigIntegerField(null=True)),
                ('m_45_plus', models.BigIntegerField(null=True)),
                ('f_45_plus', models.BigIntegerField(null=True)),
                ('tot_pop', models.BigIntegerField(null=True)),
                ('tot_hhs', models.BigIntegerField(null=True)),
                ('shape_leng', models.FloatField(null=True)),
                ('shape_le_1', models.FloatField(null=True)),
                ('shape_area', models.FloatField(null=True)),
                ('fam', models.CharField(max_length=254, null=True)),
                ('census', models.BigIntegerField(null=True)),
                ('es1', models.BigIntegerField(null=True)),
                ('es2', models.BigIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ShortestPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathid', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
